# Generated by Django 3.2.6 on 2022-01-04 02:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_Name', models.CharField(max_length=3000)),
                ('lecture_content', models.TextField(max_length=3000, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(3000)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_Name', models.CharField(max_length=1000)),
                ('course_Description', models.TextField(max_length=3000, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(3000)])),
                ('course_Image', models.FileField(upload_to='static/uploaded_Files')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.categories')),
            ],
        ),
    ]
