# Generated by Django 3.2.6 on 2022-01-04 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_courses_lectures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectures',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.courses'),
        ),
    ]
