# Generated by Django 3.2.6 on 2022-01-07 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_lectures_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lectures',
            name='course',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Lectures',
        ),
    ]
