# Generated by Django 3.2.6 on 2022-02-23 09:37

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectures',
            name='lecture_content',
            field=ckeditor.fields.RichTextField(max_length=1000, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(3000)]),
        ),
    ]
