# Generated by Django 3.2.6 on 2022-03-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_lectures_lecture_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='file',
            field=models.FileField(null=True, upload_to='static/pdf_uploads'),
        ),
    ]
