# Generated by Django 3.2.6 on 2022-03-07 13:40

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterField(
            model_name='lectures',
            name='lecture_content',
            field=ckeditor.fields.RichTextField(max_length=15000, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(15000)]),
        ),
    ]
