# Generated by Django 3.2.6 on 2022-03-07 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_auto_20220307_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='lecture_Description',
            field=models.TextField(max_length=1000, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
