# Generated by Django 3.2.6 on 2022-03-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_lectures_lecture_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectures',
            name='lecture_Description',
        ),
    ]
